### ISSUE TITLE
Lambda Registrator Docs Don't Align with Module Docs on Registry

### ISSUE THREAD

**Issue by reskin89** [hashicorp/terraform-aws-consul-lambda#53]
Two Things:

* The Lambda Registrator documentation doesn't seem to state what permissions are *required* for the lambda registrator to operate.

* The examples in the docs [here](https://developer.hashicorp.com/consul/docs/lambda/registration/automate#deploy-the-lambda-registrator) from developer.hashicorp.com show a few attributes for invoking the module, while the documentation on the [terraform registry](https://registry.terraform.io/modules/hashicorp/consul-lambda-registrator/aws/latest/submodules/lambda-registrator?tab=inputs#required-inputs) references different *required* arguments such as an `ecr_image_uri` which states I have to copy the image over to my own ECR repository?  

In the second bullet point, I'm not sure which one is accurate, and if I do need to copy a docker image to my own private ECR, is there a good terraform pattern to do this outside of creating the ECR repository, pushing to it manually/with some other method, then running the terraform with the module invocation?  It just seems like a bulky path forward to implementing this.

Depending on which one is accurate, I'll gladly submit a PR to update the proper documentation source :)

**Comment by cthain** [comment]
:wave: Hi @reskin89, thanks for raising this issue!

> The Lambda Registrator documentation doesn't seem to state what permissions are required for the lambda registrator to operate.

I agree that it is not clear from [the docs](https://developer.hashicorp.com/consul/docs/lambda) which IAM permissions are required for Lambda registrator.

We had assumed that most people using Lambda registrator to manage the automatic registration of Lambda functions would do so through the Terraform module. There are a few moving parts in AWS that need to be put in place for the integration to work correctly. You can do the setup manually, but our Terraform modules does all the requisite setup automatically. Maintaining the principle of least privilege for Lambda registrator requires tweaking the permissions based on its configuration. The [Terraform module builds the appropriate policy here](https://github.com/hashicorp/terraform-aws-consul-lambda/blob/v0.1.0-beta2/modules/lambda-registrator/main.tf#L31-L120).

> In the second bullet point, I'm not sure which one is accurate...

The docs for the Terraform module are correct. It is a restriction of AWS Lambda that Docker images can only be pulled from [private ECR repositories](https://docs.aws.amazon.com/lambda/latest/dg/images-create.html#images-upload). The other option is to set up [pull through cache rules for a private ECR](https://docs.aws.amazon.com/AmazonECR/latest/userguide/pull-through-cache.html).

We are aware that this is a sub-optimal user experience! Eventually we will add support to automate this process in the Lambda registrator Terraform module. I don't have an estimated timeline for this at the moment.

For now, here is an example of how you can [automate the process of uploading the Lambda registrator Docker image to a private ECR](https://github.com/hashicorp/terraform-aws-consul-lambda/blob/v0.1.0-beta2/test/acceptance/setup-terraform/ecr.tf). Hopefully this is useful.

Finally, we are in the process of updating and re-releasing our Lambda integration and documentation for the upcoming Consul 1.15 release. I will add these items to our list of docs updates.

Thanks!

**Comment by reskin89** [comment]
Thanks for the reply @cthain !

I see that in the main.tf now that's great for IAM! and it even allows me to pass the name in which is huge, some of us with certain Compliance require naming conventions for IAM stuff to be created.  I'll read some pull through cache docs and see if I can automate that.  

I may also submit a PR just to break up the TF files a bit, not really integral but makes it easier to follow.

Thanks again! This information is super valuable!

**Comment by reskin89** [comment]
I'd like to raise this again @cthain regarding the 1.14 docs [here](https://developer.hashicorp.com/consul/docs/v1.14.x/lambda/registration/automate#deploy-the-lambda-registrator)

They show an attribute for the registrator module `consul_extension_data_prefix` which, when looking on github, is not a valid variable for this terraform module, it doesn't exist in any version I can find, and the lambda's that rely on this to communicate into the mesh then, don't get it, and its a required environment variable.

**Comment by reskin89** [comment]
Going to close this issue and open a new one for the new issue I reported.
