### ISSUE TITLE
Invalid Config Key EnvoyExtensions

### ISSUE THREAD

**Issue by reskin89** [hashicorp/terraform-aws-consul-lambda#74]
I've been attempting to deploy the lambda registrator, and I'm getting an error:

```json
{
	"errorMessage": "1 error occurred:\n\t* Unexpected response code: 400 (Request decoding failed: 1 error occurred:\n\t* invalid config key \"EnvoyExtensions\")\n\n",
	"errorType": "Error"
}
```

However I'm not really sure where this is coming from. I'm not sure where this config key resides, double checked the proxy defaults I have in my consul servers and have no such config key, but I see a struct for it in [Consul](https://github.com/hashicorp/consul/blob/720dda7d70f2c62f0b43e9361d19a992a16f4fef/agent/structs/envoy_extension.go#L17) so I'm thinking its coming from the lambda extension layer the registrator uses potentially.  It gets triggered right after it finds a lambda, upserts it, and then stores its defaults:

```
 [INFO] Upserting Lambda: arn=arn:aws:lambda:us-east-1:REDACTED:function:lambda-test-service 
 [DEBUG] Storing service defaults config entry: arn=arn:aws:lambda:us-east-1:REDACTED:function:lambda-test-service
 [WARN] Error reconciling event: error=| Unexpected response code: 400 (Request decoding failed: 1 error occurred: | * invalid config key "EnvoyExtensions") identifier=arn:aws:lambda:us-east-1:REDACTED:function:lambda-test-service
```

Followed by the json error response.

Any help is appreciated.  Thanks!

**Comment by cthain** [comment]
Hi @reskin89, It sounds like an incompatibility between the version of Consul and the version of Lambda registrator. What versions are you using for:
- Consul
- Lambda registrator
- Lambda extension (if you're using it)

Thanks.

**Comment by reskin89** [comment]
Registrator and extension is latest 0.1.0-beta4.  Consul 1.13.6, it looks like I need to move to consul 1.14 on my servers?

**Comment by cthain** [comment]
Thanks for the additional info. The latest `0.1.0-beta4` version of Lambda registrator/extension require Consul 1.15. If you want to use Consul 1.14 you must use version `0.1.0-beta2`.

**Comment by cthain** [comment]
We don't have a compatibility matrix in our Consul docs for Lambda yet (it's still in beta) but the compatibility is mentioned in the [CHANGELOG](https://github.com/hashicorp/terraform-aws-consul-lambda/blob/main/CHANGELOG.md#010-beta3-mar-16-2023).

**Comment by reskin89** [comment]
Thanks! I'll document this.  Back to testing I go! ⌨️ 👈

**Comment by reskin89** [comment]
I went down to beta2 and consul 1.14.7 and it looks like we're in business.  Thanks!
