### ISSUE TITLE
Lambda Registrator Module Docs Are Incorrect

### ISSUE THREAD

**Issue by reskin89** [hashicorp/terraform-aws-consul-lambda#76]
The Consul 1.14 and 1.15 docs show the [following](https://developer.hashicorp.com/consul/docs/lambda/registration/automate#deploy-the-lambda-registrator) for invoking the lambda registrator module:

```hcl
module "lambda-registrator" {
   source  = "hashicorp/consul-lambda/consul-lambda-registrator"
   version = "x.y.z"
   name = "consul-lambda-registrator"
   consul_http_addr = “https://aecfe39d629774e348a9844439f5e3c1-1471365273.us-east-1.elb.amazonaws.com:8501”
   ca_cert_path = aws_ssm_parameter.ca-cert.name
   http_token_path = aws_ssm_parameter.acl-token.name
   consul_extension_data_prefix = “/lambda_extension_data”
}
```

The issue lies in the `consul_extension_data_prefix` attribute.  This attribute isn't valid for this module.  I checked the github repository as well, and it isn't a variable, it doesn't show up anywhere.

This creates an issue as trying to create lambda functions for mesh ingress fail to spin up without this set:

```
2023-06-07T16:54:47.814Z [INFO]  consul-lambda-extension: starting proxy server
2023-06-07T16:54:50.814Z [ERROR] consul-lambda-extension: processing failed with an error: error="timeout waiting for proxy to start"
2023-06-07T16:54:50.814Z [ERROR] fatal error, exiting: error="timeout waiting for proxy to start"
EXTENSION	Name: consul-lambda-extension	State: Registered	Events: [SHUTDOWN]
2023-06-07T16:54:51.755Z [INFO]  consul-lambda-extension: starting proxy server
2023-06-07T16:54:54.757Z [ERROR] consul-lambda-extension: processing failed with an error: error="timeout waiting for proxy to start"
2023-06-07T16:54:54.757Z [ERROR] fatal error, exiting: error="timeout waiting for proxy to start"
EXTENSION	Name: consul-lambda-extension	State: Registered	Events: [SHUTDOWN]
START RequestId: a6397989-2ec4-4310-ba65-259f0fcb7bca Version: $LATEST
RequestId: a6397989-2ec4-4310-ba65-259f0fcb7bca Error: exit status 1
```

Even attempting to set the lambda to use `/` as the extension data prefix (which is supposed to be the default if not set) still fails.

Where would this manually get set in the lambda registrator in the mean time?

**Comment by reskin89** [comment]
The function takes this argument just fine, its the beta2 module I used.  I'll have to do a diff here to see what my tf is downloading to see if its hitting something improperly.  I'm also not sure which version I had open on the terraform registry, as I see it on beta2.  Thanks @cthain ! seems my eyes were deceiving me again

**Comment by cthain** [comment]
@reskin89 You can configure the log level for the Lambda extension layer by setting the `LOG_LEVEL` env var on your Lambda function. For example: `LOG_LEVEL = debug`.

**Comment by cthain** [comment]
The error message that you are seeing happens if the proxy takes too long to open the listeners on the ports assigned to the upstreams.

Do you have any upstreams configured for your Lambda function via the `CONSUL_SERVICE_UPSTREAMS` env var? If so, and you have debug logging enabled, you should see a log message for each upstream, something like:

`configuring upstream, name=<service-name>, port=<service-port>`.

If you don't have any upstreams defined, I'm wondering if that's why you're seeing the error. The `consul-lambda-extension` expects at least one upstream. I did have a quick look at the code and it seems like it should work without any upstreams (I haven't validated this though).

**Comment by reskin89** [comment]
I do indeed have an upstream configured and that upstream is alive and healthy.

I also have a valid mesh gateway up and healthy

**Comment by cthain** [comment]
Are you able to provide the full log of one of the failing Lambda invocations? It would also be helpful if you can provide the env var configuration for your function (please redact any sensitive values).

**Comment by reskin89** [comment]
here's the full log:
```
2023-06-12T17:56:49.794Z [INFO]  consul-lambda-extension: starting proxy server
2023-06-12T17:56:49.794Z [DEBUG] consul-lambda-extension: configuring upstream: name=my-service-dev port=9001
2023-06-12T17:56:52.794Z [ERROR] consul-lambda-extension: processing failed with an error: error="timeout waiting for proxy to start"
2023-06-12T17:56:52.794Z [ERROR] fatal error, exiting: error="timeout waiting for proxy to start"
EXTENSION	Name: consul-lambda-extension	State: Registered	Events: [SHUTDOWN]
[ERROR] [1686592612796] LAMBDA_RUNTIME Failed to get next invocation. No Response from endpoint
2023/06/12 17:56:52 runtime_recv_invoke_failed
2023-06-12T17:56:53.767Z [INFO]  consul-lambda-extension: starting proxy server
2023-06-12T17:56:53.767Z [DEBUG] consul-lambda-extension: configuring upstream: name=my-service-dev port=9001
2023-06-12T17:56:56.770Z [ERROR] consul-lambda-extension: processing failed with an error: error="timeout waiting for proxy to start"
```

And the env vars:

```yaml
CONSUL_MESH_GATEWAY_URI: https://REDACTED
CONSUL_SERVICE_UPSTREAMS: my-service-dev:9001
CONSUL_EXTENSION_DATA_PREFIX: /lambda_extension_data
LOG_LEVEL: debug
```

**Comment by cthain** [comment]
Hhhmm.. that log is not super helpful but thanks for providing it. At least it shows that the extension is trying to open a listener on `:9001`. It appears that it can't, and that operation is timing out. Do you have anything else in your Lambda function bound to `localhost:9001`?

The only thing that I see in your config is the value for `CONSUL_MESH_GATEWAY_URI` should just be `<addr>:<port>` without the protocol, where `<addr>` is the WAN hostname or IP address that is reachable from the Lambda function. For example:

```yaml
CONSUL_MESH_GATEWAY_URI: 10.1.2.3:8443
```

The mesh gateway isn't dialed until the Lambda function connects to the proxy listener though, so this shouldn't be causing the problem you are seeing.

**Comment by reskin89** [comment]
Nothing listening on that port no, I'll remove the https:// for brevity though

**Comment by reskin89** [comment]
I also agree the logging isn't super helpful.  Is this an envoy in the layer or the consul connect built in?  It would be nice if it had a little more detail at debug level

**Comment by cthain** [comment]
It's a custom proxy we built for the Lambda extension, based on the Consul connect proxy: https://github.com/hashicorp/terraform-aws-consul-lambda/tree/v0.1.0-beta2/consul-lambda/proxy. It's pretty terse on logging, but mostly because it "just worked" during development - I had no need to debug it and I don't recall ever seeing that timeout error.

It's EOD for me but I'll have another look at the code tomorrow morning and see if I can come up with any other ideas on why this timeout might be happening.

**Comment by reskin89** [comment]
Thank you!

**Comment by reskin89** [comment]
Any ideas @cthain ? I've been messing with it for a few days to no avail.  I could try to make an after hours PR for logging potentially

**Comment by cthain** [comment]
Hi @reskin89, I looked over the code again and I cannot see anything obvious as to why this is happening. Yesterday I ran through both of my Lambda demo environments with `v0.1.0-beta2` and my Lambda functions behaved as expected. I know that's not terribly helpful in your situtation but I think these examples might be a good place for you to start. Maybe you could compare the Lambda configuration to your configuration?
- https://github.com/hashicorp/terraform-aws-consul-lambda/tree/v0.1.0-beta2/examples/lambda
- https://github.com/cthain/consul-lambda-demo/tree/v0.1.0-beta2

The first one is an example of ECS and Lambda and the second one is an example of EKS and Lambda using HashiCups.

Note that you will need to use Go < 1.20 in order to run the examples because 1.20 changed the way the `CGO_ENABLED` flag works and this causes problems on Lambda.

**Comment by reskin89** [comment]
I'm still taking a look at the examples you posted, I did however notice your upstreams have `http://` in them, I tried adding that and it results in a go parse error:

```bash
failed to parse upstream: invalid service port: strconv.Atoi: parsing \"//my-service-dev\": invalid syntax
```

  I also noticed its calling to localhost instead of a service name for an env var `UPSTREAMS`, such as [here](https://github.com/hashicorp/terraform-aws-consul-lambda/blob/fdbe55ac06b657311f086972e866d64469c8327e/examples/lambda/lambda.tf#L40)

The docs say to use `servicename:port` however. I see the proper environment variable and naming pattern for `CONSUL_SERVICE_UPSTREAMS` in the module however.

Just trying to find some continuity between these examples and the docs.

**Comment by reskin89** [comment]
I added the datacenter env variable and now I'm getting a new error, which is then followed by the timeout proxy start (I think this is the real error though):

```bash
2023-06-20T17:32:41.194Z [INFO]  consul-lambda-extension: starting proxy server
2023-06-20T17:32:41.194Z [DEBUG] consul-lambda-extension: configuring upstream: name=my-service-dev port=9001
[ERROR] [1687282371139] LAMBDA_RUNTIME Failed to get next invocation. No Response from endpoint
2023/06/20 17:32:51 runtime_recv_invoke_failed
```

I'm not sure what endpoint its referring to.  The service I'm trying to talk to or the mesh gateways

**Comment by reskin89** [comment]
I just noticed my lambda itself will log what its trying to speak to, and it didn't even get that far, so this looks like its within the layer at init prior to my code being invoked.

**Comment by reskin89** [comment]
So that Lambda Runtime error is a lambda specific error that occurred which is odd, I'm kind of at a loss here, I may just redeploy the whole thing

**Comment by reskin89** [comment]
I created a new lambda function, with a new role in python, the code is simply the basic hello world it opens with.  I added the layer and ran a test and still get the proxy timeout:

```
Response
{
  "errorMessage": "2023-06-21T15:09:01.301Z be9cb6bb-2957-46e3-bfdc-7d034f62836c Task timed out after 3.84 seconds"
}

Function Logs
2023-06-21T15:08:54.337Z [INFO]  consul-lambda-extension: starting proxy server
2023-06-21T15:08:54.337Z [DEBUG] consul-lambda-extension: configuring upstream: name=my-service-dev port=9001
2023-06-21T15:08:57.339Z [ERROR] consul-lambda-extension: processing failed with an error: error="timeout waiting for proxy to start"
2023-06-21T15:08:57.339Z [ERROR] fatal error, exiting: error="timeout waiting for proxy to start"
EXTENSION	Name: consul-lambda-extension	State: Registered	Events: [SHUTDOWN]
2023-06-21T15:08:58.299Z [INFO]  consul-lambda-extension: starting proxy server
2023-06-21T15:08:58.299Z [DEBUG] consul-lambda-extension: configuring upstream: name=my-service-dev port=9001
EXTENSION	Name: consul-lambda-extension	State: Registered	Events: [SHUTDOWN]
START RequestId: be9cb6bb-2957-46e3-bfdc-7d034f62836c Version: 1
2023-06-21T15:09:01.300Z [ERROR] consul-lambda-extension: processing failed with an error: error="timeout waiting for proxy to start"
2023-06-21T15:09:01.300Z [ERROR] fatal error, exiting: error="timeout waiting for proxy to start"
2023-06-21T15:09:01.301Z be9cb6bb-2957-46e3-bfdc-7d034f62836c Task timed out after 3.84 seconds

END RequestId: be9cb6bb-2957-46e3-bfdc-7d034f62836c
REPORT RequestId: be9cb6bb-2957-46e3-bfdc-7d034f62836c	Duration: 3840.33 ms	Billed Duration: 3000 ms	Memory Size: 128 MB	Max Memory Used: 21 MB
```

At a loss here

**Comment by cthain** [comment]
Hi @reskin89, @erichaberkorn pointed out that Lambda reserves port `9001`. [From the Lambda telemetry docs](https://docs.aws.amazon.com/lambda/latest/dg/telemetry-api.html#telemetry-api-destination):

> Lambda reserves port 9001. There are no other port number restrictions or recommendations.

This is probably why your proxy is timing out on startup. It is trying to bind to `9001` and can't because that port is already reserved/in use.

Please try a different port for your upstream and hopefully that will fix the problem.

```yaml
CONSUL_SERVICE_UPSTREAMS: my-service-dev:9123
```

**Comment by reskin89** [comment]
Woooooow thanks!  I'll give that a shot. Who would have thought...a 1 in 65536 chance

**Comment by reskin89** [comment]
That was it! Thank you @cthain and @erichaberkorn !  What a slim chance 🤦

**Comment by cthain** [comment]
Awesome, so glad to hear that you got it working!

**Comment by reskin89** [comment]
So one more thing, I noticed that my registrator isn't writing to SSM, and I think this is causing an ambiguous error in my lambda invocation saying it doesn't have permission to getparam (I'm thinking because its not there)
